name: $(Build.DefinitionName)-$(Date:yyyyMMdd)-$(BuildID)

trigger: none

variables:
  - name: ServiceConnection
    value: AzureServiceConnection

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              version: 6.0.x
              performMultiLevelLookup: true
          - task: DotNetCoreCLI@2
            displayName: dotnet publish
            inputs:
              command: publish
              publishWebProjects: true
              zipAfterPublish: true
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: webapp
  - stage: DEV
    variables:
      - name: Environment
        value: dev
    jobs:
      - deployment: Deployment
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureWebApp@1
                  displayName: Deploy to Azure
                  inputs:
                    azureSubscription: $(ServiceConnection)
                    appType: webAppLinux
                    appName: adf-csv-to-cosmos-$(Environment)
                    package: $(Pipeline.Workspace)/webapp/AdfCsvToCosmos.Web.zip